### ISSUE TITLE
[1.9] FTB Tasks issues

### ISSUE THREAD

**Issue by Steedr** [StrangeOne101/PixelTweaks#11]
## Description
Most of the tasks have some sort of bug, so here's a list of all tasks and what's wrong with them

### Catch Pokémon
Catch type `Raid` and `Pokeball Catch and Raid` remain untested since pokémon from Raid Dens can't be caught

### Defeat Pokémon
Only thing that currently doesn't work is spec boss `boss:common` `boss:epic`

### Evolve Pokémon
Evolution Cause `Item Interaction` and `Sporadically` doesn't work. Interaction was tested on Eevee -> Jolteon and Sporadically on Galarian Yamask -> Runerigus

### Level Up Pokémon
Works

### Trade Pokémon
Works, just a small thing, missing lang for `ftbquests.task.pixelmon.trade_pokemon.invert`

### Breed Pokémon
It should probably trigger when you take out pokémon, currently it's when you add requirements (items), this way Golden and Diamond Hourglass doesn't trigger the task

### Hatch Pokémon
Sometimes it works, sometimes it doesn't.
For example I have a task for blank (random), eevee and type:bug. When I've tried to hatch random pokémon it didn't trigger anything, but when I've tried Eevee it triggered both `eevee` task and blank (random)
_Note: It seems to be pixelmon issue, because with AquaPatch-1.16.5-1.0.1 it's working_

### Pokedex Ammount
Doesn't show the same number as pokédex, currently at 51, but task says 29

### Pokedex Percentage
Doesn't mark task as finished after reaching specific number, also in progress it shows only like 2 or 3% completed
Example: `Pokedex Filter=All, Percentage=3,0` In task it shows progress `3,11% / 3,00$ [3%]`
I've also tried lower number `0,3` and the result progress was `2,84% / 0,30$ [2%]`

### Pokedollars
Can't get it to work on server right now, not sure if it's a me issue or plugin's
On SinglePlayer it doesn't automatically update, only if you click directly on the task or after restart

### Whiteout
Works, but it would probably be better to rename it to Wipeout, took me some time to figure it out + I had to check in code what it actually does

### Defeat Player
Works

### Defeat Pokémon Trainer
Works

### Take Photo
Works

### Use Battle Move
`Critical Hit:true` doesn't work

### Use External Move
No matter which one you use, it triggers task for all of them

## Context
Pixelmon Version: 9.1.6
PixelTweaks Version: 1.9
Server or Single Player: Tested on both

Modpack:
architectury-1.32.68
ftb-library-forge-1605.3.4-build.90
ftb-quests-forge-1605.3.7-build.165
ftb-teams-forge-1605.2.3-build.40
item-filters-forge-1605.2.5-build.9
Pixelmon-1.16.5-9.1.6-universal
PixelTweaks-1.9

**Comment by StrangeOne101** [comment]
I wonder if a lot of these aren't updating due to the server not sending the client information. All of this would have been missed in testing as it was done mostly in single player

Thanks for reporting these. I'll try get as many as I can done

**Comment by StrangeOne101** [comment]
Fixed a lot of these issues in cf4eb552a4419b9b5538484ba900247b5a1c35ad. A lot will require further testing on a dedicated server

**Comment by Steedr** [comment]
I've updated to 1.9.1 / 9.1.7 and tried to mess with Catch Pokémon, here is something interesting.
It doesn't properly save "type" in the config, it save as `type: 0b` `1b` `2b` etc. (depends on catch type) and it probably should be `type: "pixelmon:catch_pokemon"`. That's why it always turns into Invalid quest after restart. I've tried to manually edit one quest and its working fine after a restart, just not sure where to put catch type (0b - 7b), since the default acts as `Any` (including command).
After that fix in config every spec I've tried works, but `type:` will revert back to number and break the Task after next restart.
List of specs I've tried: `species:Weedle` `Weedle` `type:bug` `leg` `ub` `shiny` `leg shiny` `ub shiny` `type:water gen:1 shiny`

Also there is a missing lang for `pixeltweaks.lang.ultrabeast`

**Comment by StrangeOne101** [comment]
In regards to catch type, I think I found the issue. The issue is that I have a variable called "type" that defines what kind of catch it is. That is what saves as 0b, 1b, etc. These are ordinal values of the list of options. I didn't realize "type" was what was used to define it in the config, so that is probably why it is breaking. I'll fix that ASAP.

> Also there is a missing lang for `pixeltweaks.lang.ultrabeast`
There is no use for this lang node as it ended up being a thing I couldn't use. These lang nodes were used to transcribe the stuff in Pokemon rewards if the first spec was "random". E.g. `random legendary` would become "Random Legendary Pokemon". However, there is no spec for Ultra Beast, so I couldn't transcribe the spec. That is why it is unused

**Comment by Steedr** [comment]
There are 3 specs for Ultra Beast that I know of: `ub` `ultrabeast` and `isultrabeast:true`
Here's an example with generated text of catching spec `shiny ub`
![image](https://github.com/StrangeOne101/PixelTweaks/assets/35104379/814880e0-72c0-4d1a-864e-e67bab26daa6)

**Comment by Steedr** [comment]
Just finished retesting **Defeat Pokemon** task and the only option that doesn't work is `Wild Pokemon Only:false` (tested on NPC and Player). If it's on `Default` or `true` it works flawlessly for every spec

**Comment by Steedr** [comment]
Can't catch pokémon from Raid Den, here's a report from the console:
https://pastebin.com/pgLexHzs
Just to note I'm on 1.9.2 / 9.1.7

**Comment by StrangeOne101** [comment]
> I couldn't get any boss spec to work `boss:uncommon`

What task did you try this on?

**Comment by Steedr** [comment]
Defeat Pokémon

**Comment by StrangeOne101** [comment]
Confirmed it doesn't work. Will look into

**Comment by StrangeOne101** [comment]
> There are 3 specs for Ultra Beast that I know of: `ub` `ultrabeast` and `isultrabeast:true` Here's an example with generated text of catching spec `ub shiny` ![image](https://user-images.githubusercontent.com/35104379/263209383-814880e0-72c0-4d1a-864e-e67bab26daa6.png)

Okay, this is bizzare

**Comment by StrangeOne101** [comment]
A lot of these should be fixed now. Everything apart from

- Sporadically evolution cause
- Breeding task trigger point
- Hatching Task
- Critical Hits in battle moves

**Comment by Steedr** [comment]
Confirm, a lot is fixed now, here is a few additional bugs

**Defeat Pokemon** - for bosses specifically (boss:common etc.) Wild Pokemon Only: false and true doesn't work, only Default. Neither does it trigger on NPC bosses (can it be even done for npc?)

**Evolve Pokemon** task using interact filter doesn't work if you specify both pokemon and item, e.g. Jolteon + Thunder Stone
Combinations that works: Jolteon + Evolution Item: (Air), Random (blank) + Evolution Item: Thunder Stone

**Reward Pokemon** - No matter what spec you have (even blank), it always crashes server
https://pastebin.com/LPRjBi9c

**Pokedex Percentage** - Filter for Type (bug, dark etc.) is wrongly saved in cofig, as `type: 10b` (0-17)
And for the progress bar, here is how it looks like, it's way beyond completion and yet still ongoing
![image](https://github.com/StrangeOne101/PixelTweaks/assets/35104379/6dbdbee5-5dd7-4408-a588-44c5e421f15e)

I've just noticed, that if you hold Shift, it shows you numbers, and that's probably what's wrong (also gen 1 should be 151)
![image](https://github.com/StrangeOne101/PixelTweaks/assets/35104379/367eb6e3-21c6-4c73-a208-5a7b2b52afb1)

**Comment by Steedr** [comment]
Another bug with Pokedollars, according to Dev of Pixelmon Economy Bridge you should be using `BankAccountProxy` to get a player's balance instead of `StorageProxy`
Here's a crash report https://pastebin.com/hE3ZwELV

**Comment by StrangeOne101** [comment]
Can you please confirm which of these are still an issue in 1.9.4?

**Comment by Steedr** [comment]
**Use Battle Move**
Critical Hit:true isn't triggered by critical moves and sometimes critical move triggers a task with Critical Hit:false

**Pokedex Amount**
Filter: Specific Pokemon + Dex Number doesn't work, it triggers on anything

**Pokedex Percentage**
The goal keeps changing with server restarts and is basically all pokémon for that Pokedex Filter (all, generation, leg, etc.) no matter the percentages.
So if you set the task to 1% of Leg & Mythical the goal should be 8,4 (8), now it's 84, sometimes it shows 81, 82, 83 after server restart

**Comment by StrangeOne101** [comment]
All should be fixed in 1.9.5 (beta available via CurseForge if you want it). Thanks for the report! It really helps!

**Comment by StrangeOne101** [comment]
Fixed in 1.9.5
